name: CD Delivery

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: make install-test
      - run: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microblog:${{ github.ref_name }}
